import { startTransition } from 'react';

/**
 * Hook to build clean, memoized or structured props for each module in AppRouter.
 * Keeps App.jsx slim, highly readable, and under 300 lines.
 */
export function useAppRouterProps({
  setCurrentTab,
  stockItems,
  machines,
  warehouseItemsComputed,
  mouvements,
  types,
  diagnostics,
  zones,
  technicians,
  operations,
  stockKPIs,
  filters,
  navigation,
  effectiveFamilies,
  effectiveTemplates,
  blueprints,
  compFamilies,
  compTemplates,
  partTypes,
  partDesignations,
  rawStock,
  designations,
  families,
  templates,
  modals: {
    setShowAddArticleModal,
    setShowAddMachineModal,
    setShowAddUserModal,
    setAddUserModalType,
    setShowAddZoneModal,
  },
  handlers: {
    handleQuickSortie,
    handleAddMouvement,
    handleUpdateMouvement,
    handleDeleteMouvement,
    handleExportExcel,
    handleUpdateArticle,
    handleDirectAdjustStock,
    handleAddWarehouseItem,
    handleUpdateWarehouseItem,
    handleDeleteWarehouseItem,
    handleAddType,
    handleUpdateType,
    handleDeleteType,
    handleAddDesignation,
    handleUpdateDesignation,
    handleDeleteDesignation,
    handleAddMachine,
    handleUpdateMachine,
    handleDeleteMachine,
    handleAddCompFamily,
    handleUpdateCompFamily,
    handleDeleteCompFamily,
    handleAddCompTemplate,
    handleUpdateCompTemplate,
    handleDeleteCompTemplate,
    handleAddPartType,
    handleUpdatePartType,
    handleDeletePartType,
    handleAddPartDesignation,
    handleUpdatePartDesignation,
    handleDeletePartDesignation,
    handleAddFamily,
    handleUpdateFamily,
    handleDeleteFamily,
    handleAddTemplate,
    handleUpdateTemplate,
    handleDeleteTemplate,
    handleAddBlueprint,
    handleUpdateBlueprint,
    handleDeleteBlueprint,
    handleAddZone,
    handleUpdateZone,
    handleDeleteZone,
    handleAddTechnician,
    handleUpdateTechnician,
    handleDeleteTechnician,
    handleAddOperation,
    handleUpdateOperation,
    handleDeleteOperation,
  },
}) {
  const navigateTo = (tab) => startTransition(() => setCurrentTab(tab));

  return {
    dashboard: {
      stockItems,
      machines,
      warehouseItems: warehouseItemsComputed,
      mouvements,
      types,
      diagnostics,
      zones,
      technicians,
      operations,
      stockKPIs,
      onNavigateToStock: () => navigateTo('stock'),
      onNavigateToMachines: () => navigateTo('machines'),
      onNavigateToWarehouse: () => navigateTo('entrepot'),
      onNavigateToSortie: () => navigateTo('sortie'),
      onNavigateToZones: () => navigateTo('zones'),
      onNavigateToUsers: () => navigateTo('utilisateurs'),
      onNavigateToSettings: () => navigateTo('settings'),
      onQuickSortie: handleQuickSortie,
      onAddMouvement: handleAddMouvement,
      onUpdateMouvement: handleUpdateMouvement,
      onDeleteMouvement: handleDeleteMouvement,
      onExportExcel: handleExportExcel,
    },

    stock: {
      stockItems,
      mouvements,
      stockSearch: filters.stockSearch,
      setStockSearch: filters.setStockSearch,
      stockTypeFilter: filters.stockTypeFilter,
      setStockTypeFilter: filters.setStockTypeFilter,
      stockAlertOnly: filters.stockAlertOnly,
      setStockAlertOnly: filters.setStockAlertOnly,
      types,
      zones,
      machines,
      technicians,
      operations,
      onOpenAddArticle: () => setShowAddArticleModal(true),
      onQuickSortie: handleQuickSortie,
      onAddMouvement: handleAddMouvement,
      onUpdateArticle: handleUpdateArticle,
      onDirectAdjustStock: handleDirectAdjustStock,
      stockKPIs,
      onNavigateToType: navigation.handleNavigateToStockFiltered,
    },

    sortie: {
      mouvements,
      stockItems,
      warehouseItems: warehouseItemsComputed,
      families,
      templates,
      types,
      diagnostics,
      zones,
      machines,
      technicians,
      operations,
      onAddMouvement: handleAddMouvement,
      onUpdateMouvement: handleUpdateMouvement,
      onDeleteMouvement: handleDeleteMouvement,
      onDirectAdjustStock: handleDirectAdjustStock,
      onAddWarehouseItem: handleAddWarehouseItem,
      onUpdateWarehouseItem: handleUpdateWarehouseItem,
      onOpenAddArticle: () => setShowAddArticleModal(true),
      onOpenAddMachine: () => setShowAddMachineModal(true),
      onOpenAddZone: () => setShowAddZoneModal(true),
      onOpenAddTech: () => {
        setAddUserModalType('TECHNICIEN');
        setShowAddUserModal(true);
      },
      onOpenAddChef: () => {
        setAddUserModalType('RESPONSABLE');
        setShowAddUserModal(true);
      },
      onOpenAddOperator: () => {
        setAddUserModalType('OPERATEUR');
        setShowAddUserModal(true);
      },
      onNavigateToWarehouse: () => navigateTo('entrepot'),
      onNavigateToStockFilteredByRef: navigation.handleNavigateToStockFilteredByRef,
    },

    entrepot: {
      warehouseItems: warehouseItemsComputed,
      mouvements,
      compFamilies,
      compTemplates,
      partTypes,
      partDesignations,
      machines,
      whSearch: filters.whSearch,
      setWhSearch: filters.setWhSearch,
      whFamilyFilter: filters.whFamilyFilter,
      setWhFamilyFilter: filters.setWhFamilyFilter,
      whTemplateFilter: filters.whTemplateFilter,
      setWhTemplateFilter: filters.setWhTemplateFilter,
      whTypeFilter: filters.whTypeFilter,
      setWhTypeFilter: filters.setWhTypeFilter,
      whNatureFilter: filters.whNatureFilter,
      setWhNatureFilter: filters.setWhNatureFilter,
      onAddWarehouseItem: handleAddWarehouseItem,
      onUpdateWarehouseItem: handleUpdateWarehouseItem,
      onDeleteWarehouseItem: handleDeleteWarehouseItem,
      onNavigateToCompFamilies: navigation.handleNavigateToCompFamilies,
      onNavigateToCompTemplates: navigation.handleNavigateToCompTemplates,
      onNavigateToPartTypes: navigation.handleNavigateToPartTypes,
      onNavigateToPartDesignations: navigation.handleNavigateToPartDesignations,
      onNavigateToEntrepotByPart: navigation.handleNavigateToEntrepotByPart,
    },

    types: {
      types,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      onAddType: handleAddType,
      onUpdateType: handleUpdateType,
      onDeleteType: handleDeleteType,
      onNavigateToDesignations: navigation.handleNavigateToDesignationsFiltered,
    },

    designations: {
      designations,
      types,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      onAddDesignation: handleAddDesignation,
      onUpdateDesignation: handleUpdateDesignation,
      onDeleteDesignation: handleDeleteDesignation,
      onOpenAddTypeModal: () => navigateTo('types'),
      onNavigateToDiag: navigation.handleNavigateToDiagFiltered,
    },

    machines: {
      machines,
      families: effectiveFamilies,
      templates: effectiveTemplates,
      blueprints,
      zones,
      technicians,
      mouvements,
      search: filters.mchSearch,
      setSearch: filters.setMchSearch,
      mchFamilyFilter: filters.mchFamilyFilter,
      setMchFamilyFilter: filters.setMchFamilyFilter,
      mchTemplateFilter: filters.mchTemplateFilter,
      setMchTemplateFilter: filters.setMchTemplateFilter,
      mchZoneFilter: filters.mchZoneFilter,
      setMchZoneFilter: filters.setMchZoneFilter,
      onAddMachine: handleAddMachine,
      onUpdateMachine: handleUpdateMachine,
      onDeleteMachine: handleDeleteMachine,
      onOpenAddMachine: () => setShowAddMachineModal(true),
      onNavigateToFamily: navigation.handleNavigateToFamilyFiltered,
      onNavigateToTemplate: navigation.handleNavigateToTemplatesFiltered,
      onNavigateToZone: navigation.handleNavigateToMachinesByZone,
      onNavigateToBlueprints: navigation.handleNavigateToBlueprintsFiltered,
    },

    compFamilies: {
      compFamilies,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      onAddCompFamily: handleAddCompFamily,
      onUpdateCompFamily: handleUpdateCompFamily,
      onDeleteCompFamily: handleDeleteCompFamily,
      onNavigateToCompTemplates: navigation.handleNavigateToCompTemplates,
    },

    compTemplates: {
      compTemplates,
      compFamilies,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      familyFilter: filters.compTemplateFamilyFilter,
      setFamilyFilter: filters.setCompTemplateFamilyFilter,
      onAddCompTemplate: handleAddCompTemplate,
      onUpdateCompTemplate: handleUpdateCompTemplate,
      onDeleteCompTemplate: handleDeleteCompTemplate,
      onOpenAddFamilyModal: () => navigateTo('comp_families'),
      onNavigateToEntrepotByComp: navigation.handleNavigateToEntrepotByComp,
    },

    partTypes: {
      partTypes,
      partDesignations,
      warehouseItems: warehouseItemsComputed,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      onAddPartType: handleAddPartType,
      onUpdatePartType: handleUpdatePartType,
      onDeletePartType: handleDeletePartType,
      onNavigateToPartDesignations: navigation.handleNavigateToPartDesignations,
      onNavigateToEntrepotByType: navigation.handleNavigateToEntrepotByType,
    },

    partDesignations: {
      partDesignations,
      partTypes,
      warehouseItems: warehouseItemsComputed,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      partDesignationTypeFilter: filters.partDesignationTypeFilter,
      setPartDesignationTypeFilter: filters.setPartDesignationTypeFilter,
      onAddPartDesignation: handleAddPartDesignation,
      onUpdatePartDesignation: handleUpdatePartDesignation,
      onDeletePartDesignation: handleDeletePartDesignation,
      onNavigateToPartTypes: navigation.handleNavigateToPartTypes,
      onNavigateToEntrepotByPart: navigation.handleNavigateToEntrepotByPart,
      onNavigateToEntrepotByType: navigation.handleNavigateToEntrepotByType,
    },

    families: {
      families: effectiveFamilies,
      templates: effectiveTemplates,
      machines,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      onAddFamily: handleAddFamily,
      onUpdateFamily: handleUpdateFamily,
      onDeleteFamily: handleDeleteFamily,
      onNavigateToTemplatesFiltered: navigation.handleNavigateToTemplatesFiltered,
      onNavigateToMachinesByFamily: navigation.handleNavigateToMachinesByFamily,
    },

    templates: {
      templates: effectiveTemplates,
      families: effectiveFamilies,
      machines,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      templateFamilyFilter: filters.templateFamilyFilter,
      setTemplateFamilyFilter: filters.setTemplateFamilyFilter,
      onAddTemplate: handleAddTemplate,
      onUpdateTemplate: handleUpdateTemplate,
      onDeleteTemplate: handleDeleteTemplate,
      onOpenAddFamilyModal: () => navigateTo('families'),
      onNavigateToMachinesByTemplate: navigation.handleNavigateToMachinesByTemplate,
      onNavigateToFamilyFiltered: navigation.handleNavigateToFamilyFiltered,
      onNavigateToBlueprints: navigation.handleNavigateToBlueprintsFiltered,
    },

    blueprints: {
      blueprints,
      templates: effectiveTemplates,
      families: effectiveFamilies,
      machines,
      compFamilies,
      compTemplates,
      partTypes,
      partDesignations,
      stockItems,
      warehouseItems: warehouseItemsComputed,
      mouvements,
      blueprintFamilyFilter: filters.blueprintFamilyFilter,
      setBlueprintFamilyFilter: filters.setBlueprintFamilyFilter,
      blueprintTemplateFilter: filters.blueprintTemplateFilter,
      setBlueprintTemplateFilter: filters.setBlueprintTemplateFilter,
      onAddBlueprint: handleAddBlueprint,
      onUpdateBlueprint: handleUpdateBlueprint,
      onDeleteBlueprint: handleDeleteBlueprint,
      onOpenAddFamilyModal: () => navigateTo('families'),
      onOpenAddTemplateModal: () => navigateTo('templates'),
      onNavigateToMachinesByTemplate: navigation.handleNavigateToMachinesByTemplate,
      onNavigateToFamily: navigation.handleNavigateToFamilyFiltered,
      onNavigateToTemplate: navigation.handleNavigateToTemplatesFiltered,
      onNavigateToTab: navigateTo,
    },

    zones: {
      zones,
      machines,
      technicians,
      operations,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      onAddZone: handleAddZone,
      onUpdateZone: handleUpdateZone,
      onDeleteZone: handleDeleteZone,
      onNavigateToTechs: navigation.handleNavigateToTechsByZone,
      onNavigateToOps: navigation.handleNavigateToOpsByZone,
      onNavigateToMachines: navigation.handleNavigateToMachinesByZone,
      onOpenAddZoneModal: () => setShowAddZoneModal(true),
    },

    utilisateurs: {
      technicians,
      operations,
      zones,
      mouvements,
      techZoneFilter: filters.techZoneFilter,
      setTechZoneFilter: filters.setTechZoneFilter,
      opZoneFilter: filters.opZoneFilter,
      setOpZoneFilter: filters.setOpZoneFilter,
      onAddTechnician: handleAddTechnician,
      onUpdateTechnician: handleUpdateTechnician,
      onDeleteTechnician: handleDeleteTechnician,
      onAddOperation: handleAddOperation,
      onUpdateOperation: handleUpdateOperation,
      onDeleteOperation: handleDeleteOperation,
      onOpenAddArticle: () => setShowAddArticleModal(true),
      onOpenAddMachine: () => setShowAddMachineModal(true),
      onOpenAddZone: () => setShowAddZoneModal(true),
      onOpenAddTechModal: () => {
        setAddUserModalType('TECHNICIEN');
        setShowAddUserModal(true);
      },
      onOpenAddRespModal: () => {
        setAddUserModalType('RESPONSABLE');
        setShowAddUserModal(true);
      },
      onOpenAddOpModal: () => {
        setAddUserModalType('OPERATEUR');
        setShowAddUserModal(true);
      },
    },

    settings: {
      rawStock,
      stockItems,
      machines,
      mouvements,
      types,
      designations,
      zones,
      technicians,
      operations,
      compFamilies,
      compTemplates,
      partTypes,
      partDesignations,
      families: effectiveFamilies,
      templates: effectiveTemplates,
      warehouseItems: warehouseItemsComputed,
      onNavigateToWarehouse: () => navigateTo('entrepot'),
    },

    nexus: {
      types,
      diagnostics,
      families: effectiveFamilies,
      templates: effectiveTemplates,
      blueprints,
      zones,
      technicians,
      operations,
      machines,
      stockItems,
      compFamilies,
      compTemplates,
      partTypes,
      partDesignations,
      warehouseItems: warehouseItemsComputed,
      mouvements,
      onNavigate: navigateTo,
    },

    guide: {},
  };
}
